from typing import Any, Dict, List, Optional, Literal
from datetime import datetime, timedelta, time
# unifi_access/managers/system_log.py

SystemLogTopic = Literal["all", "critical", "door_openings", "updates", "device_events", "admin_activity", "visitor"]

class SystemLogManager:
    """High-level manager for UniFi Access system log operations.

    Provides methods for fetching logs, exporting logs, and listing related
    resources. All HTTP I/O is delegated to `client` which must expose
    `_make_request(method, path, ...)`.
    """

    def __init__(self, client: Any) -> None:
        """Initialize the manager.

        Args:
            client: Low-level HTTP client with a `_make_request` method.
        """
        self.client = client

    def fetch_system_logs(
        self,
        topic: SystemLogTopic = "all",
        page_num: Optional[int] = None,
        page_size: Optional[int] = None,
        since: Optional[int] = None,
        until: Optional[int] = None,
        actor_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Fetch system logs using filters.

        Args:
            topic: Topic or list of topics to filter, e.g.,
                "critical", "door_openings", "updates", "device_events", "admin_activity", "visitor".
            page_num: Page number (server default if omitted).
            page_size: Page size (server default if omitted).
            since: Start of time range as Unix timestamp.
            until: End of time range as Unix timestamp.
            actor_id: Filter logs generated by a specific actor ID.

        Returns:
            API response containing the filtered system log entries.

        Notes:
            - Request URL: /developer/system/logs
            - Permission Key: view:system_log
            - Method: POST
        """

        path = "/developer/system/logs"
        params = {
            "page_num": page_num,
            "page_size": page_size,
        }
        data: Dict[str, Any] = {
            "topic": topic
        }
        if since:
            data["since"] = since
        if until:
            data["until"] = until
        if actor_id:
            data["actor_id"] = actor_id

        return self.client._make_request("POST", path, json=data, params=params)

    def export_system_logs(
        self,
        since: int,
        until: int,
        timezone: str,
        topic: SystemLogTopic = "all",
    ) -> bytes:
        """Export system logs as a file (e.g., CSV or JSON).

        Args:
            since: Start timestamp (Unix epoch) for log filtering.
            until: End timestamp (Unix epoch) for log filtering.
            timezone: Timezone identifier for log timestamps.
            topic: Topic to filter logs (e.g., "access.door.unlock").

        Returns:
            Raw file content (e.g., CSV or JSON data).

        Notes:
            - Request URL: /developer/system/logs/export
            - Permission Key: view:system_log
            - Method: POST
            - Returns raw file content instead of JSON-parsed data.
        """
        path = "/developer/system/logs/export"
        data = {
            "since": since,
            "until": until,
            "timezone": timezone,
            "topic": topic
        }

        return self.client._make_request("POST", path, json=data, raw_response=True)

    def fetch_resources_in_system_logs(
        self,
        id: Optional[str] = None,

    ) -> List[Dict[str, Any]]:
        """Fetch resources mentioned in system logs.

        Args:
            id: Resource ID is obtained from targets catergorized as the "activities_resource" type in system logs.

        Returns:
            A list of resource dictionaries.

        Notes:
            - Request URL: /developer/system/logs/resources/:id
            - Permission Key: view:system_log
            - Method: GET
        """
        path = f"/developer/system/logs/resources/{id}"

        return self.client._make_request("GET", path)

    def fetch_static_resources_in_system_logs(
        self,
        path: str
    ) -> List[Dict[str, Any]]:
        """Fetch static resources mentioned in system logs.

        Args:
            path: Path to the static resource.

        Returns:
            A list of static resource dictionaries.

        Notes:
            - Request URL: /developer/system/static/:path
            - Permission Key: view:system_log
            - Method: GET
        """
        path = f"/developer/system/static/{path}"

        return self.client._make_request("GET", path)
